##静态资源访问前缀配置
#spring:
#  mvc:
#    static-path-pattern: /res/**
##静态资源文件夹路径设置
#  web:
#    resources:
#      static-locations: [classpath:/haha/]
##是否禁用所有静态资源，false禁用，true使用
#      add-mappings: false
##缓存时间配置以秒为单位
#      cache:
#        period: 11000
#手动开启REST风格请求
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true